### ISSUE TITLE
ncd-red-comm does not install with latest stable nodejs

### ISSUE THREAD

**Issue by DaveNorth866** [ncd-io/ncd-red-comm#6]
new install on raspberry pi4 latest buster new install of node-red 1.0.3 

node -v was 12. something the latest stable release ... ncd-red-comm would not install

Reverted node back to v8.11.3 (which is the same version i am using ncd-red-comm and ncd-red-ads1115 successfully on a raspberry pi 3b) and then ncd-red-comm installs fine ncd-red-ads1115 also installs fine and works perfectly.

So conclusion ncd-red-comm has a issue with the latest stable release of nodejs

**Comment by tkanjar** [comment]
I had the same problem on raspi 3B. node -v was v12.13.1.

I fixed `package.json` file in following
```diff
  "optionalDependencies": {
-    "i2c-bus": "^3.1.0"
+    "i2c-bus": "^5.1.0"
  },
```
and run
```bash
npm update
```
the installation was succeeded.
