### ISSUE TITLE
Dependency on i2cdetect creates problems for folks using node red container.

### ISSUE THREAD

**Issue by bobrich** [ncd-io/ncd-red-comm#7]
Just an observation, the i2cdetect utility isn't available by default when folks run the node red docker container as per instructions.   When the plugin tries to execute it here:
https://github.com/ncd-io/ncd-red-comm/blob/6fde734d7e8c939bd187b1055a353cbd357fc91f/ncd-comm.js#L34  it fails and the i2c bus dropdown remains unpopulated.

Would be nice for the code to either test for the ability to execute that or provide another mechanism to enter the values.

As a workaround i just created a script of the same name that mimcs the output.  That works but is obviously super kludgy.  Thanks.

**Comment by justinSCS** [comment]
@bobrich I am running into the same issue as I am running a container system as well.  Could you share the script so maybe I could get an idea of how to fix my issue?

**Comment by zaphod-42** [comment]
Sorry for the delay, I haven't worked on this library in some time. I do not have a lot to test on, and didn't take the time to set up a container, but I added 2 fallbacks for detecting the i2c busses in 6994af80da9ee46ac3c00eb0eb1469fb95c1858b The first imitates part of the logic handled in i2cdetect, enough that it works on a raspberry pi. The second opens a blank input field in place of a select box so you can manually enter the bus number you need. Hopefully this will be enough to solve the problem, if you have any issues, feel free to reopen.

**Comment by bobrich** [comment]
> Sorry for the delay.

No worries at all, I really appreciate you taking a look at this.  I'll at least attempt a PR if anything comes up in the future, I was just running and gunning on a configuration and wanted to jot this down before I forgot it.  

Thanks again!!!
